# Mount to Google drive

In [ ]:
#mount to google drive first
import io
from google.colab import drive  
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Load Data

In [ ]:
#Data Cleaning
import pandas as pd
import numpy as np
from datetime import datetime, date #datetime stuff
import missingno as msno # for dealing with missing values

#Data Exploration
import seaborn as sns
import matplotlib.pyplot as plt

#Data modelling
from statsmodels import api as sm # tp perform regression
from scipy import stats

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
path = "/content/drive/My Drive/UNIVERSITY/Sem 4 - 2020/IFN - 704/Data/"

xls = pd.ExcelFile(path+ 'site_details.xlsx')
meta = pd.read_excel(xls, 'site_details')

In [ ]:
meta.head()

     site_id  postcode state  ... Unnamed: 4  States No. of Customers
0  515850145      2903   ACT  ...        NaN     ACT              2.0
1  739575630      2914   ACT  ...        NaN     NSW            251.0
2    2011366      2680   NSW  ...        NaN     QLD            229.0
3    2644595      2284   NSW  ...        NaN      SA            410.0
4   11320202      2525   NSW  ...        NaN     VIC             89.0

[5 rows x 7 columns]

In [ ]:
meta.describe()

            site_id     postcode  Unnamed: 4  No. of Customers
count  1.000000e+03  1000.000000         0.0          7.000000
mean   1.068847e+09  4150.119000         NaN        142.857143
std    6.238796e+08  1195.806042         NaN        157.496485
min    2.011366e+06  2022.000000         NaN          2.000000
25%    5.122392e+08  2878.000000         NaN          9.500000
50%    1.053760e+09  4504.000000         NaN         89.000000
75%    1.605063e+09  5108.000000         NaN        240.000000
max    2.147462e+09  7467.000000         NaN        410.000000

In [ ]:
meta[(meta.postcode < 4100) & (meta.postcode > 4000) ]

        site_id  postcode state  ... Unnamed: 4  States No. of Customers
255    23802476      4017   QLD  ...        NaN     NaN              NaN
263    77491219      4018   QLD  ...        NaN     NaN              NaN
270   173994775      4012   QLD  ...        NaN     NaN              NaN
274   230966412      4053   QLD  ...        NaN     NaN              NaN
275   241271752      4017   QLD  ...        NaN     NaN              NaN
279   327993590      4034   QLD  ...        NaN     NaN              NaN
291   430976744      4020   QLD  ...        NaN     NaN              NaN
302   505713029      4053   QLD  ...        NaN     NaN              NaN
313   602393300      4074   QLD  ...        NaN     NaN              NaN
315   603579184      4069   QLD  ...        NaN     NaN              NaN
319   651423412      4036   QLD  ...        NaN     NaN              NaN
325   689045440      4055   QLD  ...        NaN     NaN              NaN
326   717470730      4064   QLD  ...        NaN     NaN              NaN
327   731073921      4034   QLD  ...        NaN     NaN              NaN
328   731480064      4053   QLD  ...        NaN     NaN              NaN
333   786801023      4051   QLD  ...        NaN     NaN              NaN
340   830404513      4070   QLD  ...        NaN     NaN              NaN
350   879390244      4070   QLD  ...        NaN     NaN              NaN
355   944901235      4073   QLD  ...        NaN     NaN              NaN
357   957928559      4019   QLD  ...        NaN     NaN              NaN
358   960193414      4037   QLD  ...        NaN     NaN              NaN
359   981959413      4022   QLD  ...        NaN     NaN              NaN
373  1112438379      4055   QLD  ...        NaN     NaN              NaN
377  1150449095      4012   QLD  ...        NaN     NaN              NaN
381  1177124361      4074   QLD  ...        NaN     NaN              NaN
382  1192160560      4069   QLD  ...        NaN     NaN              NaN
383  1201849983      4060   QLD  ...        NaN     NaN              NaN
394  1313466315      4078   QLD  ...        NaN     NaN              NaN
407  1449942486      4068   QLD  ...        NaN     NaN              NaN
417  1519472386      4012   QLD  ...        NaN     NaN              NaN
421  1576347744      4078   QLD  ...        NaN     NaN              NaN
428  1639855210      4064   QLD  ...        NaN     NaN              NaN
434  1704118180      4019   QLD  ...        NaN     NaN              NaN
443  1828011983      4012   QLD  ...        NaN     NaN              NaN
465  1999038196      4018   QLD  ...        NaN     NaN              NaN
471  2071709766      4017   QLD  ...        NaN     NaN              NaN
476  2115304985      4053   QLD  ...        NaN     NaN              NaN
481  2147461500      4055   QLD  ...        NaN     NaN              NaN

[38 rows x 7 columns]

In [ ]:
import os
path = "/content/drive/My Drive/UNIVERSITY/Sem 4 - 2020/IFN - 704/Data/"

os.chdir(path)

In [ ]:

data = pd.read_csv(path + "2019-01.csv")
data2 = pd.read_csv(path + "2019-02.csv")
data3 = pd.read_csv(path + "2019-03.csv")
data4 = pd.read_csv(path + "2019-04.csv")
data5 = pd.read_csv(path + "2019-05.csv")
data6 = pd.read_csv(path + "2019-06.csv")
data7 = pd.read_csv(path + "2019-07.csv")
data8 = pd.read_csv(path + "2019-08.csv")
data9 = pd.read_csv(path + "2019-09.csv")
data10 = pd.read_csv(path + "2019-10.csv")
data11 = pd.read_csv(path + "2019-11.csv")
data12 = pd.read_csv(path + "2019-12.csv")

In [ ]:
data = data.append(data2, ignore_index=True)
data = data.append(data3, ignore_index=True)
data = data.append(data4, ignore_index=True)
data = data.append(data5, ignore_index=True)
data = data.append(data6, ignore_index=True)
data = data.append(data7, ignore_index=True)
data = data.append(data8, ignore_index=True)
data = data.append(data9, ignore_index=True)
data = data.append(data10, ignore_index=True)
data = data.append(data11, ignore_index=True)
data = data.append(data12, ignore_index=True)
data.describe()

Pick site 1

In [ ]:
solar = data[data['site_id']== 23802476]
data2 = data2[data2['site_id']== 23802476]
solar = solar.append(data2, ignore_index=True)
data3 = data3[data3['site_id']== 23802476]
solar = solar.append(data3, ignore_index=True)
data4 = data4[data4['site_id']== 23802476]
solar = solar.append(data4, ignore_index=True)
data5 = data5[data5['site_id']== 23802476]
solar = solar.append(data5, ignore_index=True)
data6 = data6[data6['site_id']== 23802476]
solar = solar.append(data6, ignore_index=True)
data7 = data7[data7['site_id']== 23802476]
solar = solar.append(data7, ignore_index=True)
data8 = data8[data8['site_id']== 23802476]
solar = solar.append(data8, ignore_index=True)
data9 = data9[data9['site_id']== 23802476]
solar = solar.append(data9, ignore_index=True)
data10 = data10[data10['site_id']== 23802476]
solar = solar.append(data10, ignore_index=True)
data11 = data11[data11['site_id']== 23802476]
solar = solar.append(data11, ignore_index=True)
data12 = data12[data12['site_id']== 23802476]
solar = solar.append(data12, ignore_index=True)

In [ ]:
solar.head()

                 t_stamp_utc   site_id  ...  voltage_max_(V)  voltage_min_(V)
0  2019-01-01 00:00:00+00:00  23802476  ...            244.0            242.3
1  2019-01-01 00:05:00+00:00  23802476  ...            244.2            242.9
2  2019-01-01 00:10:00+00:00  23802476  ...            244.4            242.1
3  2019-01-01 00:15:00+00:00  23802476  ...            244.4            242.9
4  2019-01-01 00:20:00+00:00  23802476  ...            244.3            242.8

[5 rows x 5 columns]

In [ ]:
solar.drop(columns=["voltage_max_(V)",	"voltage_min_(V)"], inplace=True)

In [ ]:
solar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105409 entries, 0 to 105408
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   t_stamp_utc  105409 non-null  object
 1   site_id      105409 non-null  int64
 2   energy_(Wh)  105409 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.4+ MB

In [ ]:
solar.describe()

          site_id    energy_(Wh)
count    105409.0  105409.000000
mean   23802476.0      70.102728
std           0.0      98.537771
min    23802476.0      -0.162200
25%    23802476.0      -0.053100
50%    23802476.0       0.065300
75%    23802476.0     134.106400
max    23802476.0     386.656700

In [ ]:
solar.to_csv("solar.csv")

#Site 2

In [ ]:
solar = data[data['site_id']== 77491219]
data2 = data2[data2['site_id']== 77491219]
solar = solar.append(data2, ignore_index=True)
data3 = data3[data3['site_id']== 77491219]
solar = solar.append(data3, ignore_index=True)
data4 = data4[data4['site_id']== 77491219]
solar = solar.append(data4, ignore_index=True)
data5 = data5[data5['site_id']== 77491219]
solar = solar.append(data5, ignore_index=True)
data6 = data6[data6['site_id']== 77491219]
solar = solar.append(data6, ignore_index=True)
data7 = data7[data7['site_id']== 77491219]
solar = solar.append(data7, ignore_index=True)
data8 = data8[data8['site_id']== 77491219]
solar = solar.append(data8, ignore_index=True)
data9 = data9[data9['site_id']== 77491219]
solar = solar.append(data9, ignore_index=True)
data10 = data10[data10['site_id']== 77491219]
solar = solar.append(data10, ignore_index=True)
data11 = data11[data11['site_id']== 77491219]
solar = solar.append(data11, ignore_index=True)
data12 = data12[data12['site_id']== 77491219]
solar = solar.append(data12, ignore_index=True)

In [ ]:
solar.head()

                 t_stamp_utc   site_id  ...  voltage_max_(V)  voltage_min_(V)
0  2019-01-01 00:00:00+00:00  77491219  ...            249.1            247.6
1  2019-01-01 00:05:00+00:00  77491219  ...            249.0            247.2
2  2019-01-01 00:10:00+00:00  77491219  ...            248.7            246.9
3  2019-01-01 00:15:00+00:00  77491219  ...            248.9            246.7
4  2019-01-01 00:20:00+00:00  77491219  ...            248.1            245.9

[5 rows x 5 columns]

In [ ]:
solar.drop(columns=["voltage_max_(V)",	"voltage_min_(V)"], inplace=True)

In [ ]:
solar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105409 entries, 0 to 105408
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   t_stamp_utc  105409 non-null  object
 1   site_id      105409 non-null  int64
 2   energy_(Wh)  105409 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.4+ MB

In [ ]:
solar.describe()

          site_id    energy_(Wh)
count    105409.0  105409.000000
mean   77491219.0      72.984006
std           0.0     109.528412
min    77491219.0    -301.730556
25%    77491219.0      -0.043600
50%    77491219.0      -0.026900
75%    77491219.0     133.578900
max    77491219.0     411.768300

In [ ]:
solar.to_csv("solar_2.csv")

In [ ]:
#from google.colab import files
#files.download('solar.csv')

# Site 3

In [ ]:
solar = data[data['site_id']== 602393300]
data2 = data2[data2['site_id']== 602393300]
solar = solar.append(data2, ignore_index=True)
data3 = data3[data3['site_id']== 602393300]
solar = solar.append(data3, ignore_index=True)
data4 = data4[data4['site_id']== 602393300]
solar = solar.append(data4, ignore_index=True)
data5 = data5[data5['site_id']== 602393300]
solar = solar.append(data5, ignore_index=True)
data6 = data6[data6['site_id']== 602393300]
solar = solar.append(data6, ignore_index=True)
data7 = data7[data7['site_id']== 602393300]
solar = solar.append(data7, ignore_index=True)
data8 = data8[data8['site_id']== 602393300]
solar = solar.append(data8, ignore_index=True)
data9 = data9[data9['site_id']== 602393300]
solar = solar.append(data9, ignore_index=True)
data10 = data10[data10['site_id']== 602393300]
solar = solar.append(data10, ignore_index=True)
data11 = data11[data11['site_id']== 602393300]
solar = solar.append(data11, ignore_index=True)
data12 = data12[data12['site_id']== 602393300]
solar = solar.append(data12, ignore_index=True)

In [ ]:
solar.head()

                 t_stamp_utc    site_id  ...  voltage_max_(V)  voltage_min_(V)
0  2019-01-01 00:00:00+00:00  602393300  ...            249.0            239.6
1  2019-01-01 00:05:00+00:00  602393300  ...            249.2            246.5
2  2019-01-01 00:10:00+00:00  602393300  ...            249.2            242.1
3  2019-01-01 00:15:00+00:00  602393300  ...            247.9            244.7
4  2019-01-01 00:20:00+00:00  602393300  ...            247.6            245.1

[5 rows x 5 columns]

In [ ]:
solar.drop(columns=["voltage_max_(V)",	"voltage_min_(V)"], inplace=True)

In [ ]:
solar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105408 entries, 0 to 105407
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   t_stamp_utc  105408 non-null  object
 1   site_id      105408 non-null  int64
 2   energy_(Wh)  105408 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.4+ MB

In [ ]:
solar.describe()

           site_id    energy_(Wh)
count     105408.0  105408.000000
mean   602393300.0      84.684022
std            0.0     118.027441
min    602393300.0      -1.910300
25%    602393300.0      -0.040800
50%    602393300.0       0.157800
75%    602393300.0     162.678600
max    602393300.0     373.493300

In [ ]:
solar.to_csv("solar_3.csv")

# Site 4

In [ ]:
solar = data[data['site_id']== 689045440]
data2 = data2[data2['site_id']== 689045440]
solar = solar.append(data2, ignore_index=True)
data3 = data3[data3['site_id']== 689045440]
solar = solar.append(data3, ignore_index=True)
data4 = data4[data4['site_id']== 689045440]
solar = solar.append(data4, ignore_index=True)
data5 = data5[data5['site_id']== 689045440]
solar = solar.append(data5, ignore_index=True)
data6 = data6[data6['site_id']== 689045440]
solar = solar.append(data6, ignore_index=True)
data7 = data7[data7['site_id']== 689045440]
solar = solar.append(data7, ignore_index=True)
data8 = data8[data8['site_id']== 689045440]
solar = solar.append(data8, ignore_index=True)
data9 = data9[data9['site_id']== 689045440]
solar = solar.append(data9, ignore_index=True)
data10 = data10[data10['site_id']== 689045440]
solar = solar.append(data10, ignore_index=True)
data11 = data11[data11['site_id']== 689045440]
solar = solar.append(data11, ignore_index=True)
data12 = data12[data12['site_id']== 689045440]
solar = solar.append(data12, ignore_index=True)

In [ ]:
solar.head()

                 t_stamp_utc    site_id  ...  voltage_max_(V)  voltage_min_(V)
0  2019-01-01 00:00:00+00:00  689045440  ...            247.8            242.8
1  2019-01-01 00:05:00+00:00  689045440  ...            247.4            238.8
2  2019-01-01 00:10:00+00:00  689045440  ...            247.0            239.1
3  2019-01-01 00:15:00+00:00  689045440  ...            246.2            236.8
4  2019-01-01 00:20:00+00:00  689045440  ...            248.6            240.5

[5 rows x 5 columns]

In [ ]:
solar.drop(columns=["voltage_max_(V)",	"voltage_min_(V)"], inplace=True)

In [ ]:
solar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105392 entries, 0 to 105391
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   t_stamp_utc  105392 non-null  object
 1   site_id      105392 non-null  int64
 2   energy_(Wh)  105392 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.4+ MB

In [ ]:
solar.describe()

           site_id    energy_(Wh)
count     105392.0  105392.000000
mean   689045440.0      79.116051
std            0.0     122.985362
min    689045440.0      -1.274400
25%    689045440.0      -0.066400
50%    689045440.0       0.063500
75%    689045440.0     120.932400
max    689045440.0     417.319700

In [ ]:
solar.to_csv("solar_4.csv")